language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install -e .[test]

script:
  - pytest test/test_hnsw.py -v

# Only test HNSW functionality
# Removed Cassandra, MongoDB, and other database dependencies
# Simplified to focus on core HNSW algorithm testing